/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import fomVe.Panel3;
import fomVe.SVGIconHelper;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author hoang
 */
public class ItemBan extends Panel3 {

    /**
     * Creates new form ItemBan
     */
    private boolean confirm = false;
    private Integer trangThai;//0:Empty-1:Full

    public ItemBan() {
        initComponents();
        SVGIconHelper.setIcon(lbAvartar, "icon/coffee-table-svgrepo-com.svg", 60, 60);

    }

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    public JLabel getLblAvatar() {
        return lbAvartar;
    }

    public void setLblAvatar(JLabel lblAvatar) {
        this.lbAvartar = lblAvatar;
    }

    public JLabel getLblSoBan() {
        return lblSoBan;
    }

    public void setLblSoBan(JLabel lblSoBan) {
        this.lblSoBan = lblSoBan;
    }

    public Integer getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }

    public void changeStateConfirm() {
        if (confirm == true) {
            confirm = false;
        } else {
            confirm = true;
        }
    }

    public JPanel getLblAvartar() {
        return lblAvartar;
    }

    public void setLblAvartar(JPanel lblAvartar) {
        this.lblAvartar = lblAvartar;
    }

    private void ColorEntered() {
        Color color = new Color(0, 153, 102);
        lblAvartar.setBackground(color);
        this.setBackground(color);
    }

    private void ColorExited() {
        Color color = new Color(102, 102, 102);
        lblAvartar.setBackground(color);
        this.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSoBan = new javax.swing.JLabel();
        lblAvartar = new javax.swing.JPanel();
        lbAvartar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));

        lblSoBan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSoBan.setForeground(new java.awt.Color(0, 255, 204));
        lblSoBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoBan.setText("01");
        lblSoBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSoBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSoBanMouseExited(evt);
            }
        });

        lblAvartar.setBackground(new java.awt.Color(102, 102, 102));
        lblAvartar.setOpaque(false);

        lbAvartar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAvartar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbAvartarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbAvartarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout lblAvartarLayout = new javax.swing.GroupLayout(lblAvartar);
        lblAvartar.setLayout(lblAvartarLayout);
        lblAvartarLayout.setHorizontalGroup(
            lblAvartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAvartar, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        lblAvartarLayout.setVerticalGroup(
            lblAvartarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblAvartarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAvartar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSoBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAvartar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblAvartar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbAvartarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvartarMouseEntered
        if (trangThai == 0) {
            ColorEntered();
        }
    }//GEN-LAST:event_lbAvartarMouseEntered

    private void lbAvartarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAvartarMouseExited
        if (trangThai == 0) {
            ColorExited();
        }
    }//GEN-LAST:event_lbAvartarMouseExited

    private void lblSoBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoBanMouseEntered
        if (trangThai == 0) {
            ColorEntered();
        }
    }//GEN-LAST:event_lblSoBanMouseEntered

    private void lblSoBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoBanMouseExited
        if (trangThai == 0) {
            ColorExited();
        }
    }//GEN-LAST:event_lblSoBanMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbAvartar;
    private javax.swing.JPanel lblAvartar;
    private javax.swing.JLabel lblSoBan;
    // End of variables declaration//GEN-END:variables
}
