/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatClientProperties;
import fomVe.Panel;
import fomVe.Panel3;
import fomVe.PanelMain;
import fomVe.SVGIconHelper;
import java.awt.AlphaComposite;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author hoang
 */
public class ItemSanPham extends Panel3 {

    /**
     * Creates new form NewJPanel1
     */
    private String id;
    private String ma;
    private Integer trangThai;
    private ImageIcon defaultAvatar;

    public ItemSanPham() {
        initComponents();
        SVGIconHelper.setIcon(lblKhuyenMaiSp, "icon/sale-free-1-svgrepo-com.svg", 60, 60);

        defaultAvatar = new ImageIcon(getClass().getClassLoader().getResource("icon/coffee.gif"));
        Image image = defaultAvatar.getImage();
        lblAvatarSp.setIcon(defaultAvatar);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMa() {
        return ma;
    }

    public void setMa(String ma) {
        this.ma = ma;
    }

    public Integer getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }

    public ImageIcon getDefaultAvatar() {
        return defaultAvatar;
    }

    public void setDefaultAvatar(ImageIcon defaultAvatar) {
        this.defaultAvatar = defaultAvatar;
    }

    public JPanel getjPanel1() {
        return pnlDetail;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.pnlDetail = jPanel1;
    }

    public JLabel getLblAvatarSp() {
        return lblAvatarSp;
    }

    public void setLblAvatarSp(JLabel lblAvatarSp) {
        this.lblAvatarSp = lblAvatarSp;
    }

    public JLabel getLblGiaSp() {
        return lblGiaTienSp;
    }

    public void setLblGiaSp(JLabel lblGiaSp) {
        this.lblGiaTienSp = lblGiaSp;
    }

    public JLabel getLblGiaTienSp2() {
        return lblGiaTienSp2;
    }

    public void setLblGiaTienSp2(JLabel lblGiaTienSp2) {
        this.lblGiaTienSp2 = lblGiaTienSp2;
    }

    public JLabel getLblSaleSp() {
        return lblKhuyenMaiSp;
    }

    public void setLblSaleSp(JLabel lblSaleSp) {
        this.lblKhuyenMaiSp = lblSaleSp;
    }

    public JLabel getLblTenKhuyenMai() {
        return lblKhuyenMai;
    }

    public void setLblTenKhuyenMai(JLabel lblTenKhuyenMai) {
        this.lblKhuyenMai = lblTenKhuyenMai;
    }

    public JLabel getLblTenSp() {
        return lbltenSp;
    }

    public void setLblTenSp(JLabel lblTenSp) {
        this.lbltenSp = lblTenSp;
    }

    public JPanel getPnlAvatar() {
        return pnlAvartar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAvartar = new javax.swing.JPanel();
        lblKhuyenMaiSp = new javax.swing.JLabel();
        lblAvatarSp = new javax.swing.JLabel();
        lblGiaTienSp2 = new javax.swing.JLabel();
        pnlDetail = new javax.swing.JPanel();
        lbltenSp = new javax.swing.JLabel();
        lblGiaTienSp = new javax.swing.JLabel();
        lblKhuyenMai = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        pnlAvartar.setBackground(new java.awt.Color(242, 242, 242));
        pnlAvartar.setOpaque(false);
        pnlAvartar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnlAvartarKeyReleased(evt);
            }
        });
        pnlAvartar.setLayout(new javax.swing.OverlayLayout(pnlAvartar));

        lblKhuyenMaiSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sale.png"))); // NOI18N
        pnlAvartar.add(lblKhuyenMaiSp);

        lblAvatarSp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatarSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/coffeePanel.gif"))); // NOI18N
        lblAvatarSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvatarSp.setMaximumSize(new java.awt.Dimension(200, 300));
        lblAvatarSp.setMinimumSize(new java.awt.Dimension(200, 300));
        lblAvatarSp.setPreferredSize(new java.awt.Dimension(200, 330));
        lblAvatarSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAvatarSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAvatarSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAvatarSpMouseExited(evt);
            }
        });
        pnlAvartar.add(lblAvatarSp);

        lblGiaTienSp2.setForeground(new java.awt.Color(242, 242, 242));
        lblGiaTienSp2.setText("jLabel1");
        pnlAvartar.add(lblGiaTienSp2);

        pnlDetail.setBackground(new java.awt.Color(242, 242, 242));
        pnlDetail.setOpaque(false);

        lbltenSp.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lbltenSp.setForeground(new java.awt.Color(0, 0, 0));
        lbltenSp.setText("Caffee");
        lbltenSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltenSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltenSpMouseExited(evt);
            }
        });

        lblGiaTienSp.setBackground(new java.awt.Color(102, 255, 255));
        lblGiaTienSp.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblGiaTienSp.setForeground(new java.awt.Color(83, 56, 44));
        lblGiaTienSp.setText("50.000");
        lblGiaTienSp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblGiaTienSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGiaTienSpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGiaTienSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGiaTienSpMouseExited(evt);
            }
        });

        lblKhuyenMai.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblKhuyenMai.setForeground(new java.awt.Color(255, 51, 51));
        lblKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhuyenMai.setText("Khuyến Mại");
        lblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhuyenMaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhuyenMaiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlDetailLayout = new javax.swing.GroupLayout(pnlDetail);
        pnlDetail.setLayout(pnlDetailLayout);
        pnlDetailLayout.setHorizontalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGiaTienSp, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lbltenSp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
            .addComponent(lblKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDetailLayout.setVerticalGroup(
            pnlDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetailLayout.createSequentialGroup()
                .addComponent(lblKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(lbltenSp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGiaTienSp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAvartar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAvartar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblAvatarSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarSpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAvatarSpMouseClicked

    private void lblAvatarSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarSpMouseEntered

    
    }//GEN-LAST:event_lblAvatarSpMouseEntered

    private void lblAvatarSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarSpMouseExited
      
   
    }//GEN-LAST:event_lblAvatarSpMouseExited

    private void pnlAvartarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlAvartarKeyReleased
     
    }//GEN-LAST:event_pnlAvartarKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
     
    }//GEN-LAST:event_formKeyReleased

    private void lbltenSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltenSpMouseEntered
    
    }//GEN-LAST:event_lbltenSpMouseEntered

    private void lbltenSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltenSpMouseExited
      
    }//GEN-LAST:event_lbltenSpMouseExited

    private void lblGiaTienSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaTienSpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblGiaTienSpMouseClicked

    private void lblGiaTienSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaTienSpMouseEntered
    }//GEN-LAST:event_lblGiaTienSpMouseEntered

    private void lblGiaTienSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGiaTienSpMouseExited
    }//GEN-LAST:event_lblGiaTienSpMouseExited

    private void lblKhuyenMaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhuyenMaiMouseEntered
    }//GEN-LAST:event_lblKhuyenMaiMouseEntered

    private void lblKhuyenMaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhuyenMaiMouseExited
    }//GEN-LAST:event_lblKhuyenMaiMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatarSp;
    private javax.swing.JLabel lblGiaTienSp;
    private javax.swing.JLabel lblGiaTienSp2;
    private javax.swing.JLabel lblKhuyenMai;
    private javax.swing.JLabel lblKhuyenMaiSp;
    private javax.swing.JLabel lbltenSp;
    private javax.swing.JPanel pnlAvartar;
    private javax.swing.JPanel pnlDetail;
    // End of variables declaration//GEN-END:variables
}
