/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import static Email.EmailForm.emailAdd;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import org.springframework.boot.SpringApplication;

import java.awt.*;
import javax.swing.BorderFactory;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import domainmodel.NhanVien;
import domainmodel.TaiKhoanAdmin;
import domainmodel.TaiKhoanNguoiDung;
import fomVe.SVGIconHelper;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URL;
import java.util.Locale;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.SwingWorker;
import org.hibernate.Session;
import org.springframework.boot.SpringApplication;
import service.ILogin;
import service.implement.LoginSerVice;
import service.implement.QuenMatKhauSevice;
import utility.Config;

import viewmodel.ChiNhanhViewModel_Hoang;
import viewmodel.NhanVienView;
import viewmodel.NhanVienViewModel_Van;

/**
 *
 * @author hoang
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ILogin logService = new LoginSerVice();
    private ChiNhanhViewModel_Hoang chiNhanh;
    private TaiKhoanNguoiDung nguoiDung;
    private boolean isFullScreen = false;
    private static FlatSVGIcon icon = null;
    static int otp1=406225;
    public static String emailAdd;
    QuenMatKhauSevice dao = new QuenMatKhauSevice();

    public static void setIcon2(JButton label, String path, int width, int height) {
        try {
            icon = new FlatSVGIcon(path, width, height);
            label.setIcon(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public Login() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setIcon2(btnDangNhap, "icon/Login.svg", 30, 30);
        setIcon2(btnclose, "icon/close.svg", 20, 20);
        setIcon2(btnToanManHinh, "icon/resize-svgrepo-com.svg", 20, 20);
        SVGIconHelper.setIcon(logo, "icon/LogoHang.svg", 30, 30);
        txtMatKhau.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    btnDangNhapActionPerformed(null);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuenMatKhau = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtTenTaiKhoan = new fomVe.JxText();
        jPanel5 = new javax.swing.JPanel();
        txtEmail = new fomVe.JxText();
        btnSendCode = new javax.swing.JButton();
        txtMaXacMinh = new fomVe.JxText();
        ps1 = new fomVe.ps1();
        ps2 = new fomVe.ps2();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblQuenMK = new javax.swing.JLabel();
        panel2 = new fomVe.Panel();
        txtMatKhau = new fomVe.Password();
        panel1 = new fomVe.Panel();
        txtTaiKhoan = new fomVe.Jtext();
        btnDangNhap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        anhNen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMinimise = new javax.swing.JButton();
        btnToanManHinh = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        QuenMatKhau.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(5, 1, 0, 5));

        txtTenTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        txtTenTaiKhoan.setOpaque(true);
        txtTenTaiKhoan.setPrompt("Mã nhân viên");
        jPanel4.add(txtTenTaiKhoan);

        jPanel5.setOpaque(false);

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setOpaque(true);
        txtEmail.setPrompt("Email");

        btnSendCode.setBackground(new java.awt.Color(51, 51, 51));
        btnSendCode.setForeground(new java.awt.Color(255, 255, 255));
        btnSendCode.setText("Send code");
        btnSendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendCode))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSendCode, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel5);

        txtMaXacMinh.setBackground(new java.awt.Color(255, 255, 255));
        txtMaXacMinh.setOpaque(true);
        txtMaXacMinh.setPrompt("Mã xác minh");
        jPanel4.add(txtMaXacMinh);

        ps1.setText("");
        jPanel4.add(ps1);

        ps2.setText("");
        jPanel4.add(ps2);

        jButton4.setBackground(new java.awt.Color(143, 45, 52));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Đổi mật khẩu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QuenMatKhauLayout = new javax.swing.GroupLayout(QuenMatKhau.getContentPane());
        QuenMatKhau.getContentPane().setLayout(QuenMatKhauLayout);
        QuenMatKhauLayout.setHorizontalGroup(
            QuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuenMatKhauLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        QuenMatKhauLayout.setVerticalGroup(
            QuenMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuenMatKhauLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Coffee so good , you");
        jPanel7.add(jLabel3);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" taste buds will");
        jPanel7.add(jLabel4);

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" love it ...");
        jPanel7.add(jLabel2);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 280, 105));

        jLabel9.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("For further details, contact team 3- Fpoly !");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Hotline :  035 . 770 . 2364");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 570, -1, -1));

        lblQuenMK.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMK.setText("Forgot password");
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseExited(evt);
            }
        });
        jPanel2.add(lblQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 100, 20));

        panel2.setBackground(new java.awt.Color(255, 255, 255));

        txtMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setBorder(null);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 280, -1));

        panel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTaiKhoan.setBorder(null);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 280, -1));

        btnDangNhap.setBackground(new java.awt.Color(155, 49, 56));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Login");
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseExited(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel2.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 280, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Log In Berks Beans Coffee");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 280, -1));

        anhNen.setBackground(new java.awt.Color(0, 0, 0));
        anhNen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/photo-1610632380989-680fe40816c6.jpg"))); // NOI18N
        jPanel2.add(anhNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, 640));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        btnMinimise.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mini.png"))); // NOI18N
        btnMinimise.setBorder(null);
        btnMinimise.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimiseActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimise);

        btnToanManHinh.setBackground(new java.awt.Color(0, 0, 0));
        btnToanManHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/to.png"))); // NOI18N
        btnToanManHinh.setBorder(null);
        btnToanManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToanManHinhActionPerformed(evt);
            }
        });
        jPanel1.add(btnToanManHinh);

        btnclose.setBackground(new java.awt.Color(0, 0, 0));
        btnclose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setBorder(null);
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimiseActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimiseActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

    }//GEN-LAST:event_jPanel2MouseClicked

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnToanManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToanManHinhActionPerformed
        GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice device = env.getDefaultScreenDevice();

        JFrame frame = (JFrame) SwingUtilities.getRoot((Component) evt.getSource());
        if (!isFullScreen) {
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            device.setFullScreenWindow(frame);
            isFullScreen = true;
        } else {
            frame.setExtendedState(JFrame.NORMAL);
            device.setFullScreenWindow(null);
            isFullScreen = false;
        }
    }//GEN-LAST:event_btnToanManHinhActionPerformed

    public TaiKhoanNguoiDung getNguoiDung() {
        return nguoiDung;
    }

    public void setNguoiDung(TaiKhoanNguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }

    public ChiNhanhViewModel_Hoang getChiNhanh() {
        return chiNhanh;
    }

    public void setChiNhanh(ChiNhanhViewModel_Hoang chiNhanh) {
        this.chiNhanh = chiNhanh;

    }

    private void lblQuenMKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseEntered
        lblQuenMK.setForeground(new Color(181, 49, 58));
    }//GEN-LAST:event_lblQuenMKMouseEntered

    private void lblQuenMKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseExited
        lblQuenMK.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblQuenMKMouseExited

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        if (!txtTaiKhoan.getText().isEmpty() || txtMatKhau.getPassword().length > 0) {
            TaiKhoanAdmin taiKhoanAdmin = logService.getAdmin(txtTaiKhoan.getText(), txtMatKhau.getText());
            TaiKhoanNguoiDung taiKhoanND = logService.getNguoiDung(txtTaiKhoan.getText(), txtMatKhau.getText());
            NhanVien nv=new NhanVien();
            if (taiKhoanAdmin != null) {
                LoadingData loading = new LoadingData(this, true);
                SwingWorker sw = new SwingWorker() {
                    @Override
                    protected Object doInBackground() throws Exception {
                        setNguoiDung(null);
                        setChiNhanh(null);
                        OverView ov = new OverView(taiKhoanAdmin, taiKhoanND);
                        ov.setVisible(true);
                        dispose();
                        return null;
                    }
                    @Override
                    protected void done() {
                        loading.dispose();
                    }
                };
                sw.execute();
                try {
                    loading.setVisible(true);
                }catch (Exception e) {
                }

            } else if (taiKhoanND != null ) {
                LoadingData loading = new LoadingData(this, true);
                SwingWorker sw = new SwingWorker() {
                    @Override
                    protected Object doInBackground() throws Exception {
                        setNguoiDung(taiKhoanND);
                        NhanVien nv = logService.getNhanVienbyTaiKhoan(taiKhoanND.getId());
                        System.out.println("dm0");
                        setChiNhanh(logService.getChiNhanhByNhanVien(nv.getId()));
                        System.out.println("dm1");
                        OverView ov = new OverView(taiKhoanAdmin, taiKhoanND);
                        System.out.println("dm");
                        ov.setVisible(true);
                        dispose();
                        return null;
                    }

                    @Override
                    protected void done() {
                        loading.dispose();
                    }
                };
                sw.execute();
                loading.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không đúng");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tài khoản mật khẩu");
        }


    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {
        QuenMatKhau.setVisible(true);
        QuenMatKhau.setSize(365, 305);
        QuenMatKhau.setBackground(new Color(102, 102, 102));
        QuenMatKhau.setLocationRelativeTo(null);
    }

    private void btnSendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendCodeActionPerformed
        try {
            if (!txtEmail.getText().isEmpty()) {
                LoadingData loading = new LoadingData(this, true);
                SwingWorker worker = new SwingWorker<>() {
                    @Override
                    protected Object doInBackground() throws Exception {
                        Random random = new Random();
                        int min = 100000;
                        int max = 999999;
                        //otp = random.nextInt(max - min) + min;
                        emailAdd = txtEmail.getText();
                        SpringApplication.run(EmailApplication.class, new String[0]);

                        return null;
                    }

                    @Override
                    protected void done() {
                        loading.dispose();
                        JOptionPane.showMessageDialog(null, "Success");
                    }
                };
                worker.execute();
                loading.setVisible(true);

                //  btnSendCode.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(QuenMatKhau, "Email không được để trống");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(QuenMatKhau, "Email không tồn tại !");
        }

    }//GEN-LAST:event_btnSendCodeActionPerformed
    boolean ChekValidate() {
        String tenTk = txtTenTaiKhoan.getText();
        TaiKhoanNguoiDung tk = dao.selectById(tenTk);
        String otpInput = txtMaXacMinh.getText();
        int otp2;
        try {
            otp2 = Integer.parseInt(otpInput);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(QuenMatKhau, "Mã xác minh không hợp lệ");
            return false;
        }
        String matkhauMoi = new String(ps1.getPassword());
        String matkhauMoi2 = new String(ps2.getPassword());

        if (tenTk.trim().equals("") || txtEmail.getText().trim().equals("") || otpInput.trim().equals("") || matkhauMoi.trim().equals("") || matkhauMoi2.trim().equals("")) {
            JOptionPane.showMessageDialog(QuenMatKhau, "Thiếu dữ liệu");
            return false;
        }
        if (tk == null) {
            JOptionPane.showMessageDialog(QuenMatKhau, "Tài khoản không tồn tại");
            return false;
        } else if (otp2 != otp1) {
            JOptionPane.showMessageDialog(QuenMatKhau, "Sai mã xác minh");
            return false;
        } else if (!matkhauMoi.equals(matkhauMoi2)) {
            JOptionPane.showMessageDialog(QuenMatKhau, "Mật khẩu không giống nhau");
            return false;
        }

        return true;
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (ChekValidate()) {
            String tenTk = txtTenTaiKhoan.getText();
            TaiKhoanNguoiDung tk = dao.selectById(tenTk);
            tk.setMatKhau(ps2.getText());
            dao.update(tk);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            QuenMatKhau.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
        setIcon2(btnDangNhap, "icon/Login.svg", 36, 36);
        Font originalFont = btnDangNhap.getFont();
        Font boldFont = new Font(originalFont.getFontName(), Font.PLAIN, originalFont.getSize() + 2);
        btnDangNhap.setFont(boldFont);
    }//GEN-LAST:event_btnDangNhapMouseEntered

    private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
        setIcon2(btnDangNhap, "icon/Login.svg", 30, 30);
        Font originalFont = btnDangNhap.getFont();
        Font boldFont = new Font(originalFont.getFontName(), Font.PLAIN, originalFont.getSize() + -2);
        btnDangNhap.setFont(boldFont);
    }//GEN-LAST:event_btnDangNhapMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {

        if (utility.Config.createDefaultConfigFile()) {

            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
            } catch (UnsupportedLookAndFeelException ex) {
                ex.printStackTrace();
            }

            UIManager.put("Button.arc", 15);
            UIManager.put("Component.arc", 10);
            UIManager.put("TextComponent.arc", 10);
            new Login().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "tao file tại :" + utility.Config.isConfigFileCreated() + "!!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog QuenMatKhau;
    private javax.swing.JLabel anhNen;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnMinimise;
    private javax.swing.JButton btnSendCode;
    private javax.swing.JButton btnToanManHinh;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JLabel logo;
    private fomVe.Panel panel1;
    private fomVe.Panel panel2;
    private fomVe.ps1 ps1;
    private fomVe.ps2 ps2;
    private fomVe.JxText txtEmail;
    private fomVe.JxText txtMaXacMinh;
    private fomVe.Password txtMatKhau;
    private fomVe.Jtext txtTaiKhoan;
    private fomVe.JxText txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
